import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'n8n-automation-thumbnail',
    title: 'n8n Automation Workflow',
    tagline: 'Visualizing Complex Automations',
    thumbnailUrl: 'https://i.postimg.cc/q73kMw9X/n8n.jpg',
    images: ['https://i.postimg.cc/q73kMw9X/n8n.jpg'],
    client: 'Automation Agency',
    challenge: 'Create a clear and engaging thumbnail for a tutorial video about building complex workflows in n8n, a workflow automation tool.',
    solution: 'The design uses the n8n logo and brand colors to create immediate recognition. A screenshot of a complex workflow is featured prominently, with key nodes highlighted to hint at the tutorial\'s value. The overall look is clean and technical, appealing to the target audience of developers and automators.',
    tools: ['n8n', 'Figma', 'Adobe Photoshop'],
  },
  {
    id: 'valorant-reyna-thumbnail',
    title: 'Valorant Reyna Montage',
    tagline: 'High-Impact Gaming Thumbnail',
    thumbnailUrl: 'https://i.postimg.cc/3NSMZ0sh/reyna2.jpg',
    images: ['https://i.postimg.cc/3NSMZ0sh/reyna2.jpg'],
    client: 'Valorant Content Creator',
    challenge: 'Create a dynamic and eye-catching thumbnail for a Valorant gameplay montage featuring the agent Reyna. The thumbnail needed to stand out in a saturated niche.',
    solution: 'The design features a high-action shot of Reyna, enhanced with dramatic lighting, glow effects, and a bold, modern font. The color palette is aligned with the character\'s in-game abilities to create a cohesive and visually appealing thumbnail.',
    tools: ['Adobe Photoshop', 'Figma'],
  },
  {
    id: 'boise-travel-thumbnail',
    title: 'Travel Vlog Thumbnail',
    tagline: 'Discovering Boise, Idaho',
    thumbnailUrl: 'https://i.postimg.cc/P5Rf10DH/boise.jpg',
    images: ['https://i.postimg.cc/P5Rf10DH/boise.jpg'],
    client: 'Adventure Vlogger',
    challenge: 'Create an inviting and professional thumbnail for a travel vlog about exploring Boise, Idaho. The design needed to capture the city\'s vibe and entice viewers to watch.',
    solution: 'The design uses a high-quality photo of the vlogger against a recognizable Boise landmark. Bold, clean text with a subtle drop shadow ensures readability, while a warm color grade gives the thumbnail a friendly and adventurous feel.',
    tools: ['Adobe Photoshop', 'Lightroom'],
  },
  {
    id: 'zero-to-hero-thumbnail',
    title: 'Zero to Hero Transformation',
    tagline: 'Visualizing an epic journey',
    thumbnailUrl: 'https://i.postimg.cc/wBHcYhfF/wwdpsb.jpg',
    images: ['https://i.postimg.cc/wBHcYhfF/wwdpsb.jpg'],
    client: 'Story-driven Content Creator',
    challenge: 'Create a thumbnail that encapsulates a long and difficult journey, showing the starting point and the triumphant end.',
    solution: 'A split-screen design contrasts the humble beginnings with the ultimate success, using color grading and dramatic imagery to tell a compelling visual story.',
    tools: ['Adobe Photoshop', 'Lightroom'],
  },
  {
    id: 'abstract-gradient-thumbnail',
    title: 'Abstract Gradient Design',
    tagline: 'Vibrant visuals for digital branding',
    thumbnailUrl: 'https://i.postimg.cc/BvS3LV7Y/efeff.jpg',
    images: ['https://i.postimg.cc/BvS3LV7Y/efeff.jpg'],
    client: 'Digital Art Collective',
    challenge: 'Create a visually striking thumbnail using abstract shapes and a vibrant color gradient that can be used for a variety of digital content, from music videos to podcast covers.',
    solution: 'The design uses a dynamic composition of flowing lines and a bold, colorful gradient to create a sense of energy and motion. The high-contrast elements ensure it stands out on any platform.',
    tools: ['Adobe Photoshop', 'Figma'],
  },
  {
    id: 'zohocrm-tutorial-thumbnail',
    title: 'Zoho CRM Tutorial Thumbnail',
    tagline: 'Professional Visuals for Business Content',
    thumbnailUrl: 'https://i.postimg.cc/76Kp2PGc/zohocrm.jpg',
    images: ['https://i.postimg.cc/76Kp2PGc/zohocrm.jpg'],
    client: 'SaaS Marketing Channel',
    challenge: 'Create a clean, professional thumbnail for a Zoho CRM tutorial that appeals to a business audience and clearly communicates the video\'s content.',
    solution: 'The design uses Zoho\'s brand colors and logos to establish immediate recognition. A clean layout with bold, readable text highlights the topic, making it look both professional and clickable.',
    tools: ['Figma', 'Adobe Photoshop'],
  },
  {
    id: 'coherence-movie-thumbnail',
    title: 'Movie Analysis Thumbnail',
    tagline: 'Deep Dive into "Coherence"',
    thumbnailUrl: 'https://i.postimg.cc/63ScPKzm/coherence.jpg',
    images: ['https://i.postimg.cc/63ScPKzm/coherence.jpg'],
    client: 'FilmBuff Edits',
    challenge: 'Create a captivating thumbnail for a deep-dive video analysis of the complex sci-fi film "Coherence." The design needed to hint at the movie\'s confusing, mind-bending nature without giving away spoilers.',
    solution: 'The design uses a fragmented, collage-style layout with key characters looking distressed or confused. A dark, moody color palette with a single bright color for the text creates a sense of mystery and urgency, compelling viewers to click and understand the film\'s secrets.',
    tools: ['Adobe Photoshop', 'Figma'],
  },
  {
    id: 'esports-tournament-thumbnail',
    title: 'Esports Tournament Grand Finals',
    tagline: 'High-stakes competition visual',
    thumbnailUrl: 'https://i.postimg.cc/v8WYcf3L/competition.jpg',
    images: ['https://i.postimg.cc/v8WYcf3L/competition.jpg'],
    client: 'Gaming League Network',
    challenge: 'Design a dynamic thumbnail for a major esports tournament final that conveys the intensity and prestige of the event.',
    solution: 'The thumbnail features the team captains in a dramatic face-off, with fiery particle effects and bold, metallic text to create a sense of epic confrontation.',
    tools: ['Adobe Photoshop', 'Figma'],
  },
  {
    id: 'ai-finance-thumbnail',
    title: 'AI Finance Thumbnail',
    tagline: 'Bold visuals for a viral finance topic',
    thumbnailUrl: 'https://i.postimg.cc/FRrfDpPw/dana5.jpg',
    images: ['https://i.postimg.cc/FRrfDpPw/dana5.jpg'],
    client: 'FinTech Guru',
    challenge: 'Design a thumbnail for a video about AI tools for financial independence, making a bold claim to attract viewers in a competitive niche.',
    solution: 'The design centers on a clear, high-dollar figure on a mobile interface, combined with an expressive reaction from the host. Floating currency and subtle AI iconography reinforce the theme.',
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
  },
  {
    id: 'anime-livestream-thumbnail',
    title: 'Anime Livestream Thumbnail',
    tagline: 'Dynamic art for a gaming livestream',
    thumbnailUrl: 'https://i.postimg.cc/9FCWT0kh/evol-thumb.png',
    images: ['https://i.postimg.cc/9FCWT0kh/evol-thumb.png'],
    client: 'Evol Yash Gaming',
    challenge: 'Create an energetic thumbnail for a "Road to 1K" BGMI livestream, featuring a popular anime character to draw in a specific audience.',
    solution: 'A dynamic illustration of a famous anime warrior is combined with bold, high-contrast text. A "LIVE" indicator and branding elements are integrated to create a professional and urgent call to action.',
    tools: ['Adobe Photoshop', 'Canva'],
  },
  {
    id: 'got-fan-poster',
    title: 'Game of Thrones Fan Poster',
    tagline: 'Winter is Coming... Again',
    thumbnailUrl: 'https://i.postimg.cc/FRxhnQd5/got.jpg',
    images: ['https://i.postimg.cc/FRxhnQd5/got.jpg'],
    client: 'Fan Art Commission',
    challenge: 'Create a poster that captures the dark and epic tone of the Game of Thrones universe, focusing on a central character.',
    solution: 'A highly detailed digital painting with dramatic lighting, focusing on the character\'s intense expression. The color palette is cold and desaturated to evoke the feeling of winter.',
    tools: ['Adobe Photoshop', 'Wacom Tablet'],
  },
   {
    id: 'fantasy-character-concept',
    title: 'Fantasy Character Concept',
    tagline: 'The Guardian of the Enchanted Forest',
    thumbnailUrl: 'https://i.postimg.cc/J06MMc5G/lichen.jpg',
    images: ['https://i.postimg.cc/J06MMc5G/lichen.jpg'],
    client: 'Indie Game Studio',
    challenge: 'Design a memorable character for an upcoming fantasy RPG. The character needed to look wise, ancient, and connected to nature.',
    solution: 'Developed a concept of a forest guardian with bark-like skin and glowing magical elements. The use of earthy tones and bioluminescent highlights brought the character to life.',
    tools: ['Procreate', 'Adobe Photoshop'],
  },
  {
    id: 'podcast-thumbnail-design',
    title: 'Podcast Thumbnail Template',
    tagline: 'Engaging Visuals for Audio Content',
    thumbnailUrl: 'https://i.postimg.cc/Zn744FxM/p1.jpg',
    images: ['https://i.postimg.cc/Zn744FxM/p1.jpg'],
    client: 'The Round Table Podcast',
    challenge: 'Create a versatile thumbnail template that could be easily updated for weekly podcast episodes, featuring different guests and topics.',
    solution: 'Designed a template with designated areas for guest photos, episode titles, and branding. The bold typography and contrasting colors ensure it stands out in a crowded feed.',
    tools: ['Figma', 'Adobe Photoshop'],
  },
  {
    id: 'reaction-video-thumbnail',
    title: 'Reaction Video Thumbnail',
    tagline: 'Maximizing Click-Through Rate',
    thumbnailUrl: 'https://i.postimg.cc/PxKkQz9J/sample69.jpg',
    images: ['https://i.postimg.cc/PxKkQz9J/sample69.jpg'],
    client: 'YouTube Content Creator',
    challenge: 'Design a high-energy thumbnail for a reaction video that immediately conveys shock and curiosity.',
    solution: 'Used a split-screen layout to show the subject of the reaction and the creator\'s exaggerated expression. Bright colors, bold outlines, and minimal text create an immediate impact.',
    tools: ['Adobe Photoshop', 'Canva'],
  },
  {
    id: 'challenge-video-thumbnail',
    title: 'Challenge Video Thumbnail',
    tagline: 'Explosive Visuals for Viral Content',
    thumbnailUrl: 'https://i.postimg.cc/7h6rsJrL/sccsd12.jpg',
    images: ['https://i.postimg.cc/7h6rsJrL/sccsd12.jpg'],
    client: 'Viral Content House',
    challenge: 'Create a thumbnail for a "Last to Leave" challenge that feels dramatic and exciting.',
    solution: 'A composition filled with color and explosive effects frames the contestants. The use of high-contrast lighting and a sense of action helps to generate intrigue and clicks.',
    tools: ['Adobe Photoshop'],
  },
  {
    id: 'movie-poster-parody',
    title: 'Movie Poster Parody',
    tagline: 'Thumbnail for Film Review Channel',
    thumbnailUrl: 'https://i.postimg.cc/y6QHJj06/tiger2.jpg',
    images: ['https://i.postimg.cc/y6QHJj06/tiger2.jpg'],
    client: 'Cinema Critique YT',
    challenge: 'Design a YouTube thumbnail that mimics a blockbuster movie poster for a film review.',
    solution: 'Recreated the style of the "Tiger 3" movie poster, incorporating the channel\'s host into the design. This parody style is eye-catching and clearly communicates the video\'s topic.',
    tools: ['Adobe Photoshop'],
  },
  {
    id: 'productivity-hack-thumbnail',
    title: 'Productivity Hack Thumbnail',
    tagline: 'Unlock Your Potential',
    thumbnailUrl: 'https://i.postimg.cc/CMX9msfx/thum11b2-(2).jpg',
    images: ['https://i.postimg.cc/CMX9msfx/thum11b2-(2).jpg'],
    client: 'Self-Help Guru',
    challenge: 'Design a thumbnail that visually represents the idea of breaking free from constraints and achieving success.',
    solution: 'The design uses a powerful color contrast and symbolic imagery of a person breaking through a barrier. Bold text highlights the key benefit, creating a strong and motivational message.',
    tools: ['Adobe Photoshop', 'Figma'],
  },
  {
    id: 'emotional-story-thumbnail',
    title: 'Emotional Story Thumbnail',
    tagline: 'A Story of Despair and Hope',
    thumbnailUrl: 'https://i.postimg.cc/QtPYYjVd/img-(7)-(1).webp',
    images: ['https://i.postimg.cc/QtPYYjVd/img-(7)-(1).webp'],
    client: 'Documentary Channel',
    challenge: 'Create a thumbnail that conveys a powerful emotional journey, contrasting a low point with a moment of triumph or peace.',
    solution: 'A split-screen composition with dramatic color grading on each side effectively tells a story of transformation. The high-contrast emotions in the imagery create immediate intrigue.',
    tools: ['Adobe Photoshop', 'Lightroom'],
  },
  {
    id: 'fitness-transformation-thumbnail',
    title: 'Fitness Transformation',
    tagline: 'From Beginner to Beast',
    thumbnailUrl: 'https://i.postimg.cc/GtFPPRyg/vitali2ty-(1).jpg',
    images: ['https://i.postimg.cc/GtFPPRyg/vitali2ty-(1).jpg'],
    client: 'Vitality Fitness',
    challenge: 'Design a motivational thumbnail for a fitness transformation video that is both inspiring and aspirational.',
    solution: 'The thumbnail features a high-energy shot of the subject in peak physical condition. Strong, clean typography and a vibrant color overlay create a powerful and professional look.',
    tools: ['Adobe Photoshop', 'Canva'],
  },
  {
    id: 'cyborg-character-thumbnail',
    title: 'Futuristic Cyborg Character',
    tagline: 'Sci-Fi Gaming Thumbnail Design',
    thumbnailUrl: 'https://i.postimg.cc/SKnv6XNV/enhanced-buzzji2.png',
    images: ['https://i.postimg.cc/SKnv6XNV/enhanced-buzzji2.png'],
    client: 'Sci-Fi Game Streamer',
    challenge: 'Create a high-impact thumbnail featuring a custom cyborg character for a gaming channel. The goal was to create a visually stunning image that would stand out and attract viewers interested in futuristic games.',
    solution: 'The design features a detailed illustration of the cyborg character with glowing neon elements and a dark, moody background. The high contrast and cinematic lighting give it a professional and eye-catching look, perfect for the gaming niche.',
    tools: ['Adobe Photoshop', 'Blender'],
  },
];

export const SOCIAL_LINKS = [
  { name: 'Instagram', url: 'https://www.instagram.com/hekardesigns?igsh=eXducDZtd2d5N2Nn' },
  { name: 'WhatsApp', url: 'https://wa.me/+919821318726' },
  { name: 'Telegram', url: 'https://t.me/HekarOp321' },
  { name: 'Discord', url: 'https://discord.gg/35Xewzh7' },
];


/*
// === PLACEHOLDER PROJECTS ===
// You can uncomment and use these when you have more thumbnails to add.

  {
    id: 'tshirt-graphics',
    title: 'T-Shirt Graphics',
    tagline: 'Streetwear Collection for "Urban Thread"',
    thumbnailUrl: 'https://picsum.photos/seed/animlogo/800/450',
    images: ['https://picsum.photos/seed/animlogo/800/450'],
    client: 'Urban Thread Apparel',
    challenge: 'Design a series of bold, original graphics for a new line of streetwear t-shirts targeting a young, urban audience.',
    solution: 'The collection features a mix of typographic designs, abstract illustrations, and photo-based graphics, all with a consistent edgy and modern aesthetic.',
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
  },
  {
    id: 'animated-logo',
    title: 'Animated Logo',
    tagline: 'Logo Sting for "Nexus Media"',
    thumbnailUrl: 'https://picsum.photos/seed/animlogo/800/450',
    images: ['https://picsum.photos/seed/animlogo-detail1/1200/800'],
    client: 'Nexus Media',
    challenge: 'Create a short, memorable logo animation to be used as an intro/outro for video content.',
    solution: 'We designed a fluid and dynamic animation where the logo elements resolve in a clean and satisfying way, accompanied by custom sound design to enhance the impact.',
    tools: ['Adobe After Effects', 'Adobe Audition'],
  },
  {
    id: 'product-photography-retouching',
    title: 'Product Photo Retouching',
    tagline: 'High-End Retouching for "Aura Beauty"',
    thumbnailUrl: 'https://picsum.photos/seed/retouching/800/450',
    images: ['https://picsum.photos/seed/retouching-detail1/1200/800'],
    client: 'Aura Beauty',
    challenge: 'Perform high-end retouching on a series of product and model photographs for a luxury cosmetics campaign, ensuring a flawless but natural look.',
    solution: 'Utilizing advanced techniques like frequency separation and non-destructive dodging and burning, we enhanced the images while preserving realistic skin texture, resulting in polished and professional final assets.',
    tools: ['Adobe Photoshop', 'Capture One'],
  },
  {
    id: 'wayfinding-signage',
    title: 'Wayfinding Signage',
    tagline: 'Campus Signage for "Innovate Corp"',
    thumbnailUrl: 'https://picsum.photos/seed/signage/800/450',
    images: ['https://picsum.photos/seed/signage-detail1/1200/800'],
    client: 'Innovate Corp Campus',
    challenge: 'Design a clear and intuitive wayfinding system for a large corporate campus to improve navigation for employees and visitors.',
    solution: 'We developed a cohesive system of signs using clear typography, a simple color-coding scheme, and universal icons. The design is both functional and aesthetically aligned with the company\'s modern architecture.',
    tools: ['Adobe Illustrator'],
  },
  {
    id: 'presentation-design',
    title: 'Presentation Design',
    tagline: 'Keynote for "Tech Summit 2024"',
    thumbnailUrl: 'https://picsum.photos/seed/presentation/800/450',
    images: ['https://picsum.photos/seed/presentation-detail1/1200/800'],
    client: 'Keynote Speaker at Tech Summit',
    challenge: 'Design a visually stunning and impactful slide deck for a keynote presentation that would keep the audience engaged for 45 minutes.',
    solution: 'We moved away from text-heavy slides and focused on strong visuals, custom infographics, and a consistent narrative flow. The result was a professional, cinematic presentation that effectively supported the speaker\'s message.',
    tools: ['Figma', 'Keynote', 'Google Slides'],
  },
  {
    id: 'coffee-packaging',
    title: 'Coffee Packaging',
    tagline: 'Artisanal Bags for "Ground Control"',
    thumbnailUrl: 'https://picsum.photos/seed/coffee/800/450',
    images: ['https://picsum.photos/seed/coffee-detail1/1200/800'],
    client: 'Ground Control Roasters',
    challenge: 'Design packaging for a new line of single-origin coffee beans that reflects the brand\'s commitment to quality and storytelling.',
    solution: 'Each bag features a unique illustration and color palette inspired by the coffee\'s origin country, creating a collectible series that stands out on the shelf.',
    tools: ['Adobe Illustrator', 'Procreate'],
  },
  {
    id: 'ui-kit-saas',
    title: 'SaaS UI Kit',
    tagline: 'Design System for "FlowState"',
    thumbnailUrl: 'https://picsum.photos/seed/uikit/800/450',
    images: ['https://picsum.photos/seed/uikit-detail1/1200/800'],
    client: 'FlowState CRM',
    challenge: 'Create a comprehensive UI kit and design system to ensure consistency and speed up development for a growing SaaS platform.',
    solution: 'We built a robust system of reusable components, styles, and guidelines in Figma, including buttons, forms, modals, and data tables. This has become the single source of truth for both design and development teams.',
    tools: ['Figma', 'Storybook'],
  },
  {
    id: 'poster-series',
    title: 'Film Festival Posters',
    tagline: 'Poster Series for "IndieReel Fest"',
    thumbnailUrl: 'https://picsum.photos/seed/poster/800/450',
    images: ['https://picsum.photos/seed/poster-detail1/1200/800', 'https://picsum.photos/seed/poster-detail2/1200/800'],
    client: 'IndieReel Film Festival',
    challenge: 'Design a series of three posters for an independent film festival, with each poster representing a different film genre (Drama, Sci-Fi, Comedy).',
    solution: 'A cohesive visual theme was established using a consistent typographic treatment and layout, while each poster uses a unique color palette and central illustration to capture the essence of its genre.',
    tools: ['Adobe Illustrator', 'Adobe Photoshop'],
  },
  {
    id: 'album-art',
    title: 'Album Art',
    tagline: 'Cover for "Neon Echoes"',
    thumbnailUrl: 'https://picsum.photos/seed/album/800/450',
    images: ['https://picsum.photos/seed/album-detail1/1200/800'],
    client: 'The Midnight Bloom (Band)',
    challenge: 'Create album artwork for a synth-pop band that feels both nostalgic and futuristic.',
    solution: 'The final design is a surreal digital collage that blends retro-futuristic landscapes with ethereal figures, perfectly matching the band\'s atmospheric sound.',
    tools: ['Adobe Photoshop', 'Blender'],
  },
  {
    id: 'annual-report',
    title: 'Annual Report',
    tagline: 'Corporate Report for "Momentum Inc."',
    thumbnailUrl: 'https://picsum.photos/seed/report/800/450',
    images: ['https://picsum.photos/seed/report-detail1/1200/800'],
    client: 'Momentum Inc.',
    challenge: 'Design a 50-page annual report that presents financial data and company achievements in a way that is engaging and easy to read for stakeholders.',
    solution: 'We used a strong grid system, clean typography, and custom data visualizations to create a professional and highly readable report. Strategic use of photography helped to break up the text and tell the company\'s story.',
    tools: ['Adobe InDesign', 'Adobe Illustrator'],
  }

*/
